# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site 站点信息
title: CoderChen's Blog
subtitle: 留心处处皆学问，人情练达即文章
description: 脚踏实地，积少成多，集腋成裘
keywords: java database linux
author: CoderChen
language: zh-CN
timezone: UTC

# URL 访问地址
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://coderChenMing.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory 目录
source_dir: source
public_dir: public
tag_dir: tags #标签
archive_dir: archives #归档
category_dir: categories #类别
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing 文章
new_post_name: :title.md # 	新文章的文件名称
default_layout: post # 预设布局
titlecase: false # 把标题转换为 title case
external_link: # 在新标签中打开链接
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5  # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next
# theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:coderChenMing/coderChenMing.github.io.git
  branch: master

# Extensions
## Plugins: http://hexo.io/plugins/
# plugins: hexo-generate-feed

# RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
# 配置站内搜索
search:
  path: search.json
  field: post
  format: html
  limit: 10000
# 阅读全文设置
# (1)使用npm安装hexo-excerpt
# npm install hexo-excerpt --save
# (2)在站点配置文件中添加如下
excerpt:
  depth: 3
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

highlight_theme: normal
  normal
  night
  night eighties
  night blue
  night bright